#!/usr/bin/env bash

get_volume() {
    MUTE=$(pamixer --get-mute)
    VOL=$(pamixer --get-volume)

    if [[ "$MUTE" == "true" ]]; then
      STATUS="muted"
    else
      STATUS="unmuted"
    fi

    printf '{"status":"%s", "level":%s}\n' "$STATUS" "$VOL"
}

get_volume

pactl subscribe | while read -r event; do
    if echo "$event" | grep -q "on sink"; then
        get_volume
    fi
done 